modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"
[[mods]]
modId = "laboratoryblocks"
version = "${file.jarVersion}"
displayName = "Artemis' Laboratory Blocks"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/artemis-laboratory-blocks"
logoFile = "artemis_laboratory_blocks-logo.png"
logoBlur = true
authors="Artemis"
description = '''
Get ready to upgrade your builds! This mod adds modern and futuristic looking laboratory blocks. Plus, it's compatible with CTM (ConnectedTexturesMod) for even better visuals.
'''
[[dependencies.laboratoryblocks]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.laboratoryblocks]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"
